jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"
  globalNodeProperties:
  - envVars:
      env:
      - key: VAR_1
        value: hello

  nodes:
    - permanent:
        name: "master"
        remoteFS: "/home/jenkins/master_agent"
        launcher:
          jnlp:
            workDirSettings:
              disabled: true
              failIfWorkDirIsMissing: false
              internalDir: "remoting"
              workDirPath: "/tmp"

  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

  securityRealm:
      local:
        users:
          - id: admin
            name: admin
            password: admin

jobs:
  - script: >
      pipelineJob('DeployJenkins') {
        triggers {
          scm('* * * * *')
        }
        definition {
          cps {
            script("""\
              node(label any) {
                deleteDir()
                stage('Deploy Jenkins') {
                  git(url: 'https://github.com/ichernysheff/jenkins-base', 
                    branch: 'master')
                  sh(label: 'Update Jenkins config', 
                    script: '''
                      rm /home/jenkins/casc_configs/jenkins.yml
                      cp ./jcasc/jenkins.yml /home/jenkins/casc_configs/jenkins.yml
                      curl -X POST 127.0.0.1:8080/configuration-as-code/reload
                    ''')
                }
              }""".stripIndent())
          }
        }
      }
